<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

In [115]:
import os

In [116]:
datos = os.listdir()
datos

['.git', 'laboratorio-modulo2-leccion01-numpy.ipynb', 'README.md']

In [117]:
diccioanrio_df = {diccioanrio_df[re.findall("\d{4}", i)[0]] : pd.read_csv(f"..dato/{i}") for i in datos}

diccioanrio_df = {}
for i in datos:
    df = pd.read_csv(i)
    diccioanrio_df[i.spl]


NameError: name 'diccioanrio_df' is not defined

for i in datos
# Laboratorio de NumPy

In [ ]:
import numpy as np 

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [ ]:

# definimos una lista que usaremos para convertir en array unidimensional
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print("La lista a partir de la que crearemos un array unidimensional es:", lista)

# convertimos la lista en array usando el método 'np.array()' 
array_unidimensional = np.array(lista)
print(f"El array unidimensional creado a partir de la lista es: \n  {array_unidimensional} \n")

La lista a partir de la que crearemos un array unidimensional es: [1, 2, 3, 4, 5, 6, 7, 8, 9]
El array unidimensional creado a partir de la lista es: 
  [1 2 3 4 5 6 7 8 9] 



#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [ ]:
# Creo un array unimensional
array_unidimensional = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,10])

# Convierto a un array de 2 dimensiones con 2 filas y 5 columnas:
array_bidimensional = array_unidimensional.reshape(2, 5)

print(array_bidimensional)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [ ]:
# Sobre el array dado hago un np.where para encontrar valores distintos a 0.
array_elementos = np.array([0, 25, 0, 44, 0, 3, 0])
print(array_elementos)
elementos_distintos_zero = np.where(array_elementos != 0)
print(elementos_distintos_zero)


[ 0 25  0 44  0  3  0]
(array([1, 3, 5]),)


#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [ ]:
array_3x3 = np.random.rand(3,3)
print(array_3x3)


[[0.87994606 0.96005175 0.55301484]
 [0.6321355  0.81356815 0.8563021 ]
 [0.84678422 0.68852179 0.87103707]]


#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [ ]:
# Creo el array aleatorio con random randint.
array_aleatorio = np.random.randint(0, 150, size=10)

# Encontrar el valor máximo y mínimo
valor_maximo = np.max(array_aleatorio)
valor_minimo = np.min(array_aleatorio)

print(f"Array Aleatorio:", array_aleatorio)
print(f"Valor Máximo del array:", valor_maximo)
print(f"Valor Mínimo del array:", valor_minimo)


Array Aleatorio: [ 34 136  16  96 103  85  68 125  33  19]
Valor Máximo del array: 136
Valor Mínimo del array: 16


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [ ]:
array_unidimensional
print(array_unidimensional)
array_ivertido = np.flip(array_unidimensional)
print(array_ivertido)

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]



#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [ ]:
# Genero con random randint el array, dandole los parametros pedidos y eligiendo matriz, filas y columnas y lo printeo
array_tridimensional = np.random.randint(0,25,(2,3,4))
print(array_tridimensional)

[[[ 1 16 19  4]
  [ 1 17 18 11]
  [16  5 24 15]]

 [[20 15  1 12]
  [11 10  5 11]
  [ 7  6  5 23]]]


In [ ]:
# Printeo primero la pirmera matriz
print(array_tridimensional[0])
# Printeo la primera matriz, fila 3 y columna 4 que es donde esta el primer 15
print(f"accedemos al primer 15:{array_tridimensional[0,2,3]}")
# Printeo todo el array
print(f"me pides que selecciones todo el array :\n {array_tridimensional}")
# Selecciono la ultima fila del ultimo array
print(f"accedemos a la ultima fila {array_tridimensional[1,2]}")



[[ 1 16 19  4]
 [ 1 17 18 11]
 [16  5 24 15]]
accedemos al primer 15:15
me pides que selecciones todo el array :
 [[[ 1 16 19  4]
  [ 1 17 18 11]
  [16  5 24 15]]

 [[20 15  1 12]
  [11 10  5 11]
  [ 7  6  5 23]]]
accedemos a la ultima fila [ 7  6  5 23]



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [ ]:
# Genero el array como me piden de 3 matrizes , 2 filas y 5 columnnas y que sus numeros sean del 1 al 30
array_tridimensional_1 = np.random.randint(0,31,(3,2,5))
print(array_tridimensional_1)

[[[21 14 25 24  1]
  [18 17 10 30 21]]

 [[15 13 26 30 30]
  [25 27 12  7  1]]

 [[15 14 29 10 27]
  [14 24 29 27 16]]]


In [128]:
# Me pide que imprima los dos primeros elementos de cada fila de la primera matriz.
print(f"Printeo los 2 primeros elementos de la primera matriz:\n {array_tridimensional_1[0,:,:2]}")

Printeo los 2 primeros elementos de la primera matriz:
 [[21 14]
 [18 17]]


In [136]:
# Selecciono la ultima filas de las 2 ultimas matrices 
print(array_tridimensional_1[1:,-1,:])

[[25 27 12  7  1]
 [14 24 29 27 16]]


#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [137]:
# Genero el array como me piden de 4 matrizes , 3 filas y 2 columnnas y que sus numeros sean del 1 al 24
array_tridimensional_2 = np.random.randint(0,24,(4,3,2))
print(array_tridimensional_2)

[[[ 6 20]
  [ 6 17]
  [ 2  8]]

 [[ 2  8]
  [ 5 10]
  [ 6 15]]

 [[19  9]
  [23 20]
  [ 1  1]]

 [[18 17]
  [14 15]
  [17  0]]]


In [139]:
# Cambio los elemendtos de la segunda fila del segundo array por 0.
array_tridimensional_2[1, 1, :] = 0
print(array_tridimensional_2)


[[[ 6 20]
  [ 6 17]
  [ 2  8]]

 [[ 2  8]
  [ 0  0]
  [ 6 15]]

 [[19  9]
  [23 20]
  [ 1  1]]

 [[18 17]
  [14 15]
  [17  0]]]


In [141]:
# Cambio todos los elementos del ultimo array a -1.
array_tridimensional_2[3,:,:] = -1
print(array_tridimensional_2)

[[[ 6 20]
  [ 6 17]
  [ 2  8]]

 [[ 2  8]
  [ 0  0]
  [ 6 15]]

 [[19  9]
  [23 20]
  [ 1  1]]

 [[-1 -1]
  [-1 -1]
  [-1 -1]]]



#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [149]:
# Genero el array como me piden de 2 matrizes , 4 filas y 3 columnnas y que sus numeros sean del 1 al 24
array_tridimensional_3 = np.random.randint(-10,14,(2,4,3))
print(array_tridimensional_3)

[[[ 2 11 11]
  [-6  7  3]
  [ 1 10 -5]
  [ 1 -3 -3]]

 [[11 13 -4]
  [-2 -8 11]
  [12 -6  1]
  [ 6  3  8]]]


In [ ]:
# Selecciono los valores mayores a 5.
elementos_mayores_5 = array_tridimensional_3[array_tridimensional_3 >5]
print(elementos_mayores_5)

[11 11  7 10 11 13 11 12  6  8]


In [152]:
# Ahora cambio los datos negativos en 0
array_tridimensional_3[array_tridimensional_3<0]=0
print(array_tridimensional_3)

[[[ 2 11 11]
  [ 0  7  3]
  [ 1 10  0]
  [ 1  0  0]]

 [[11 13  0]
  [ 0  0 11]
  [12  0  1]
  [ 6  3  8]]]


#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [153]:
# Genero el array como me piden de 3 matrizes , 3 filas y 3 columnnas y que sus numeros sean del 1 al 27
array_tridimensional_4 = np.random.randint(1,28,(3,3,3))
print(array_tridimensional_4)

[[[24 21 17]
  [ 7 17  7]
  [16  6 16]]

 [[22 25 14]
  [12 15 17]
  [ 3 10  6]]

 [[14 22 19]
  [12 23  5]
  [24 23 16]]]


In [154]:
# Selecciono el segundo array que contenga los 2 primeras columnas.
print(array_tridimensional_4[1,:,:2])

[[22 25]
 [12 15]
 [ 3 10]]


In [167]:
# Selleciono todos los elementos del tercer array que sean mayores que 20.
print(array_tridimensional_4[2,array_tridimensional_4[2]>20])

[22 23 24 23]


#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.