<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

In [71]:
import os

In [72]:
datos = os.listdir()
datos

['.git', 'laboratorio-modulo2-leccion01-numpy.ipynb', 'README.md']

In [73]:
diccioanrio_df = {diccioanrio_df[re.findall("\d{4}", i)[0]] : pd.read_csv(f"..dato/{i}") for i in datos}

diccioanrio_df = {}
for i in datos:
    df = pd.read_csv(i)
    diccioanrio_df[i.spl]


NameError: name 'diccioanrio_df' is not defined

for i in datos
# Laboratorio de NumPy

In [ ]:
import numpy as np 

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [ ]:

# definimos una lista que usaremos para convertir en array unidimensional
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print("La lista a partir de la que crearemos un array unidimensional es:", lista)

# convertimos la lista en array usando el método 'np.array()' 
array_unidimensional = np.array(lista)
print(f"El array unidimensional creado a partir de la lista es: \n  {array_unidimensional} \n")

La lista a partir de la que crearemos un array unidimensional es: [1, 2, 3, 4, 5, 6, 7, 8, 9]
El array unidimensional creado a partir de la lista es: 
  [1 2 3 4 5 6 7 8 9] 



#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [ ]:
# Creo un array unimensional
array_unidimensional = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,10])

# Convierto a un array de 2 dimensiones con 2 filas y 5 columnas:
array_bidimensional = array_unidimensional.reshape(2, 5)

print(array_bidimensional)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [ ]:
# Sobre el array dado hago un np.where para encontrar valores distintos a 0.
array_elementos = np.array([0, 25, 0, 44, 0, 3, 0])
print(array_elementos)
elementos_distintos_zero = np.where(array_elementos != 0)
print(elementos_distintos_zero)


[ 0 25  0 44  0  3  0]
(array([1, 3, 5]),)


#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [ ]:
array_3x3 = np.random.rand(3,3)
print(array_3x3)


[[0.93805186 0.47939196 0.67294039]
 [0.87832642 0.57000866 0.88598637]
 [0.16917751 0.42097143 0.85402987]]


#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [ ]:
# Creo el array aleatorio con random randint.
array_aleatorio = np.random.randint(0, 150, size=10)

# Encontrar el valor máximo y mínimo
valor_maximo = np.max(array_aleatorio)
valor_minimo = np.min(array_aleatorio)

print(f"Array Aleatorio:", array_aleatorio)
print(f"Valor Máximo del array:", valor_maximo)
print(f"Valor Mínimo del array:", valor_minimo)


Array Aleatorio: [128  21   5  29 117 101 124 109  97  67]
Valor Máximo del array: 128
Valor Mínimo del array: 5


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [ ]:
array_unidimensional
print(array_unidimensional)
array_ivertido = np.flip(array_unidimensional)
print(array_ivertido)

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]



#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [ ]:
# Genero con random randint el array, dandole los parametros pedidos y eligiendo matriz, filas y columnas y lo printeo
array_tridimensional = np.random.randint(0,25,(2,3,4))
print(array_tridimensional)

[[[15 20 21 10]
  [ 3  5 10 11]
  [ 8 20  1 14]]

 [[12 10  0 12]
  [16 24  5  7]
  [ 6 22  7 15]]]


In [ ]:
# Printeo primero la pirmera matriz
print(array_tridimensional[0])
# Printeo la primera matriz, fila 3 y columna 4 que es donde esta el primer 15
print(f"accedemos al primer 15:{array_tridimensional[0,2,3]}")
# Printeo todo el array
print(f"me pides que selecciones todo el array :\n {array_tridimensional}")
# Selecciono la ultima fila del ultimo array
print(f"accedemos a la ultima fila {array_tridimensional[1,2]}")



[[15 20 21 10]
 [ 3  5 10 11]
 [ 8 20  1 14]]
accedemos al primer 15:14
me pides que selecciones todo el array :
 [[[15 20 21 10]
  [ 3  5 10 11]
  [ 8 20  1 14]]

 [[12 10  0 12]
  [16 24  5  7]
  [ 6 22  7 15]]]
accedemos a la ultima fila [ 6 22  7 15]



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [ ]:
# Genero el array como me piden de 3 matrizes , 2 filas y 5 columnnas y que sus numeros sean del 1 al 30
array_tridimensional_1 = np.random.randint(0,31,(3,2,5))
print(array_tridimensional_1)

[[[26 20 22  6  1]
  [ 9 24  3  8  8]]

 [[ 8  3 12 27 15]
  [11 16  9  5  5]]

 [[21  8 14 17 27]
  [10  6 20 14  8]]]


In [ ]:
# Me pide que imprima los dos primeros elementos de cada fila de la primera matriz.
print(f"Printeo los 2 primeros elementos de la primera matriz:\n {array_tridimensional_1[0,:,:2]}")

Printeo los 2 primeros elementos de la primera matriz:
 [[26 20]
 [ 9 24]]


In [ ]:
# Selecciono la ultima filas de las 2 ultimas matrices 
print(array_tridimensional_1[1:,-1,:])

[[11 16  9  5  5]
 [10  6 20 14  8]]


#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [ ]:
# Genero el array como me piden de 4 matrizes , 3 filas y 2 columnnas y que sus numeros sean del 1 al 24
array_tridimensional_2 = np.random.randint(0,24,(4,3,2))
print(array_tridimensional_2)

[[[ 1 16]
  [17 19]
  [10  0]]

 [[12  4]
  [ 1 14]
  [14 10]]

 [[ 1 16]
  [16 17]
  [17 23]]

 [[19  1]
  [17 12]
  [20 22]]]


In [ ]:
# Cambio los elemendtos de la segunda fila del segundo array por 0.
array_tridimensional_2[1, 1, :] = 0
print(array_tridimensional_2)


[[[ 1 16]
  [17 19]
  [10  0]]

 [[12  4]
  [ 0  0]
  [14 10]]

 [[ 1 16]
  [16 17]
  [17 23]]

 [[19  1]
  [17 12]
  [20 22]]]


In [ ]:
# Cambio todos los elementos del ultimo array a -1.
array_tridimensional_2[3,:,:] = -1
print(array_tridimensional_2)

[[[ 1 16]
  [17 19]
  [10  0]]

 [[12  4]
  [ 0  0]
  [14 10]]

 [[ 1 16]
  [16 17]
  [17 23]]

 [[-1 -1]
  [-1 -1]
  [-1 -1]]]



#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [ ]:
# Genero el array como me piden de 2 matrizes , 4 filas y 3 columnnas y que sus numeros sean del 1 al 24
array_tridimensional_3 = np.random.randint(-10,14,(2,4,3))
print(array_tridimensional_3)

[[[ -8  -3  13]
  [ -1  -6   7]
  [ -2  -5   1]
  [ -4  -9  -9]]

 [[  8 -10   4]
  [ -3  -3   1]
  [ -8   6  -9]
  [ 13   0  12]]]


In [ ]:
# Selecciono los valores mayores a 5.
elementos_mayores_5 = array_tridimensional_3[array_tridimensional_3 >5]
print(elementos_mayores_5)

[13  7  8  6 13 12]


In [ ]:
# Ahora cambio los datos negativos en 0
array_tridimensional_3[array_tridimensional_3<0]=0
print(array_tridimensional_3)

[[[ 0  0 13]
  [ 0  0  7]
  [ 0  0  1]
  [ 0  0  0]]

 [[ 8  0  4]
  [ 0  0  1]
  [ 0  6  0]
  [13  0 12]]]


#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [ ]:
# Genero el array como me piden de 3 matrizes , 3 filas y 3 columnnas y que sus numeros sean del 1 al 27
array_tridimensional_4 = np.random.randint(1,28,(3,3,3))
print(array_tridimensional_4)

[[[25  4 15]
  [15 10 20]
  [17 19  5]]

 [[24 20 15]
  [25 12 17]
  [15 24 18]]

 [[26 26  7]
  [ 6  6 22]
  [11 19 13]]]


In [ ]:
# Selecciono el segundo array que contenga los 2 primeras columnas.
print(array_tridimensional_4[1,:,:2])

[[24 20]
 [25 12]
 [15 24]]


In [ ]:
# Selleciono todos los elementos del tercer array que sean mayores que 20.
print(array_tridimensional_4[2,array_tridimensional_4[2]>20])

[26 26 22]


#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [ ]:
# Creo un array unidimensional de 10 numeros aleatorios localizo cual es el min y el max del array.
array_uni= np.random.randint(1,50,(10))
print(array_uni)
minimo = np.min(array_uni) 
maximo = np.max(array_uni)
print(f"el valor minimo es: {minimo}")
print(f"El valor maximo del array es: {maximo}")
# Ahora cambiamos los valores a min y max a 0
array_uni[array_uni == minimo] = 0
array_uni[array_uni == maximo] = 0
print(array_uni)


[10  7 23 33 12 40 15 38 28 44]
el valor minimo es: 7
El valor maximo del array es: 44
[10  0 23 33 12 40 15 38 28  0]


#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [ ]:
# Creo un array de 15 numeros aleatorios entre 1 y 100 y lo ordeno
array_uni1= np.random.randint(1,101,(15))
print(array_uni)
array_uni1= np.sort(array_uni1)
print(array_uni1)

[16 57 82 49  9 63 38 88 48 79 87 37 14 94 65]
[12 19 36 44 45 50 51 51 53 53 64 68 78 84 88]


#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [76]:
# Creo un array de 4 filas y 4 columnas y sumo sus elementos a lo largo de la fila.
array_suma = np.random.randint(1,40,(4,4))
print(array_suma)
suma_columnas = np.sum(array_suma, axis = 0)
print(f"Sumamos las columnas {suma_columnas}")
suma_filas = np.sum(array_suma, axis = 1)
print(f"Sumamos las filas: {suma_filas}")

[[38 22 19 24]
 [19  5 17 28]
 [ 9  7  6  9]
 [ 4 30 38  6]]
Sumamos las columnas [70 64 80 67]
Sumamos las filas: [103  69  31  78]


#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [82]:
# Creo una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0

array_bordes = np.zeros((5, 5))

# Establecer los bordes de la matriz como 1
array_bordes[0, :] = 1  
array_bordes[4, :] = 1  
array_bordes[:, 0] = 1  
array_bordes[:, 4] = 1 

print(array_bordes)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [89]:
# Creo el array y calcula la media y la desviación estarndar
array_aleatorio1 = np.random.randint(1,50,(10))
print(array_aleatorio1)
calculo_media = np.median(array_aleatorio1)
print(calculo_media)
calculo_varianza = np.var(array_aleatorio1)
print(calculo_varianza)


[ 8 23  5 31 29 22  6  2 25 27]
22.5
112.96


#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [94]:
# Genero un array trimidensional de 2 matrices, 3 filas y 4 columnas - con valores del 1 al 24

array_tridimensional_5 = np.random.randint(1, 25,(2,3,4))
print(array_tridimensional_5)
# Y ahora utilizo la funcion np.transpose para que se intercambien los ejes.
array_transpuesto = np.transpose(array_tridimensional_5)
print(array_transpuesto)

[[[16 17 17 13]
  [ 2 12 17  9]
  [10 19 11  7]]

 [[18 13 10 16]
  [ 2 16 24  4]
  [ 5  6  8 22]]]
[[[16 18]
  [ 2  2]
  [10  5]]

 [[17 13]
  [12 16]
  [19  6]]

 [[17 10]
  [17 24]
  [11  8]]

 [[13 16]
  [ 9  4]
  [ 7 22]]]


## Explicación

  Como podemos ver ha pasado de un array de 2 matrices, 3 filas y 4 columnas, se ha transpuesto a un array de 4 matrices, 3 filas y 2 columnas. Por lo que se han transpuesto las columnas  con las matrices. 

#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [110]:
# Genero un array tridimensional de 3 matrices 4 filas y 2 columnas con valores del 1 al 24
tridimensional = np.random.randint(1, 25, (3,4,2))
print(tridimensional)
# Ahora transpongo el array para que sea 4,3,2
transpuesto = np.transpose(tridimensional, (1, 0, 2))
print(f"Después de hacer el transpose:\n {transpuesto}")

[[[24 13]
  [ 8 14]
  [14 24]
  [15 15]]

 [[23  6]
  [ 1  5]
  [21 21]
  [11 13]]

 [[17 12]
  [20 19]
  [21  1]
  [23  5]]]
Después de hacer el transpose:
 [[[24 13]
  [23  6]
  [17 12]]

 [[ 8 14]
  [ 1  5]
  [20 19]]

 [[14 24]
  [21 21]
  [21  1]]

 [[15 15]
  [11 13]
  [23  5]]]


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [119]:
tri_array = np.random.randint(1,25,(3,2,4))
print(tri_array)
rotacion = np.transpose(tri_array, (2, 0, 1))
print(f"Rotacion total del array: {rotacion}")

[[[16 15 16 13]
  [ 5  3 19  7]]

 [[20  3  1 12]
  [10  4 21  6]]

 [[11  7  2  5]
  [24  8  9 20]]]
Rotacion total del array: [[[16  5]
  [20 10]
  [11 24]]

 [[15  3]
  [ 3  4]
  [ 7  8]]

 [[16 19]
  [ 1 21]
  [ 2  9]]

 [[13  7]
  [12  6]
  [ 5 20]]]


#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [121]:

# Creo un array tridimensional de  (3, 4, 5) con números aleatorios entre -10 y 10
array = np.random.randint(-10, 11, (3, 4, 5))
print(array)

# Calculo: mediana, máximo y mínimo
media = np.median(array)
maximo = np.max(array)
minimo = np.min(array)

# Creo un array vacío con la misma forma que el array original
array_vacio = np.empty_like(array, dtype=object)

# Rellenar el nuevo array con las condiciones
array_vacio[array == media] = "M"
array_vacio[array > media] = "X"
array_vacio[array < media] = "Y"
array_vacio[array == maximo] = "MAX"
array_vacio[array == minimo] = "MIN"

print(array_vacio)


[[[ -4  -2  -8  -9   0]
  [-10  -2   7  -4   6]
  [  8   5 -10  -8  -9]
  [  7  -8  -6  -8   5]]

 [[  6   7  -5   6  -2]
  [ -1  -5 -10  -1  -6]
  [ -5   5   6   3   1]
  [ -1  -8   1   1   4]]

 [[  3  -2   3  -7  -7]
  [  6 -10 -10   6  -6]
  [ -7   5   5   0   3]
  [  0  -6  -3   9   6]]]
[[['Y' 'Y' 'Y' 'Y' 'X']
  ['MIN' 'Y' 'X' 'Y' 'X']
  ['X' 'X' 'MIN' 'Y' 'Y']
  ['X' 'Y' 'Y' 'Y' 'X']]

 [['X' 'X' 'Y' 'X' 'Y']
  ['M' 'Y' 'MIN' 'M' 'Y']
  ['Y' 'X' 'X' 'X' 'X']
  ['M' 'Y' 'X' 'X' 'X']]

 [['X' 'Y' 'X' 'Y' 'Y']
  ['X' 'MIN' 'MIN' 'X' 'Y']
  ['Y' 'X' 'X' 'X' 'X']
  ['X' 'Y' 'Y' 'MAX' 'X']]]


#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.

In [334]:

# Creo un array bidimensional de  4x4 con valores  entre 1 y 10
bidi_array = np.random.randint(1, 11, (4, 4))
print(bidi_array)

coincidencias = False

# Hacemos un bucle que recorra todas las filas
for filas in range(bidi_array.shape[0]): 
    fila = bidi_array[filas, :]  
# Ahora recorremos las columnas
    for columnas in range(bidi_array.shape[1]):  
        columna = bidi_array[:, columnas]  
        
# Comparamos elemento por elemento
        if all(fila[i] == columna[i] for i in range(len(fila))):
            coincidencias = True
            print(f"Fila {fila} coincide con la columna {columna}: {fila}")
            break
    if coincidencias:
        break

if not coincidencias:
    print("No hay coincidencias.")


[[5 7 9 5]
 [4 1 9 9]
 [9 7 1 2]
 [6 8 4 3]]
No hay coincidencias.
